# Form implementation generated from reading ui file 'M:\Mk_Coding\lang_Python\Projects\Eve-Classification-Model/Ui/eve_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1838, 552)
        MainWindow.setStyleSheet("border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.046, x2:1, y2:0.972, stop:0 rgba(229, 253, 255, 255), stop:0.994318 rgba(131, 250, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.187, y1:0.478, x2:0.907689, y2:0.813, stop:0 rgba(255, 255, 255, 226), stop:0.994318 rgba(199, 199, 199, 197));\n"
"background-color: qlineargradient(spread:pad, x1:0.187, y1:0.478, x2:0.907689, y2:0.813, stop:0 rgba(255, 255, 255, 239), stop:0.994318 rgba(215, 215, 215, 217));\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_bg = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 1060, 552))
        self.label_bg.setText("")
        self.label_bg.setPixmap(QtGui.QPixmap("M:\\Mk_Coding\\lang_Python\\Projects\\Eve-Classification-Model/Ui\\bg_img.png"))
        self.label_bg.setObjectName("label_bg")
        self.label_inputImages = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_inputImages.setGeometry(QtCore.QRect(353, 130, 331, 211))
        self.label_inputImages.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_inputImages.setText("")
        self.label_inputImages.setScaledContents(True)
        self.label_inputImages.setObjectName("label_inputImages")
        self.pushButton_importPics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_importPics.setGeometry(QtCore.QRect(350, 130, 334, 211))
        self.pushButton_importPics.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(True)
        self.pushButton_importPics.setFont(font)
        self.pushButton_importPics.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250, 198, 255);\n"
"    background-color: rgb(253, 235, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(253, 238, 255);\n"
"    font: 8pt \"Rupee Foradian\";\n"
"}")
        self.pushButton_importPics.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_importPics.setObjectName("pushButton_importPics")
        self.pushButton_classify = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_classify.setGeometry(QtCore.QRect(400, 410, 241, 61))
        self.pushButton_classify.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        self.pushButton_classify.setFont(font)
        self.pushButton_classify.setStyleSheet("QPushButton {\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(250, 198, 255);\n"
"    border: 3px solid black;\n"
"    border-color: rgba(0, 0 ,0,0.6);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border: 4px solid black;\n"
"    font: 87 13pt \"Segoe UI Black\";\n"
"    background-color: rgba(255, 255, 0,0.7);\n"
"\n"
"}")
        self.pushButton_classify.setObjectName("pushButton_classify")
        self.pushButton_close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"border: 2px solid black;\n"
"border-color: rgba(0,0,0,0.4);\n"
"color: rgba(72, 72, 72,0.7);\n"
"background-color: rgba(255, 138, 169,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"color: rgb(72, 72, 72);\n"
"background-color: rgb(255, 138, 169);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    background-color: rgb(255, 228, 230);\n"
"}\n"
"")
        self.pushButton_close.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_minimize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_minimize.setGeometry(QtCore.QRect(50, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_minimize.setFont(font)
        self.pushButton_minimize.setStyleSheet("QPushButton {\n"
"border: 2px solid black;\n"
"border-color: rgba(0,0,0,0.4);\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(170, 255, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 14pt \"Segoe UI Black\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    color: rgb(222, 222, 222);\n"
"    background-color: rgb(102, 104, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_minimize.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.pushButton_askEve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_askEve.setGeometry(QtCore.QRect(759, 290, 112, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_askEve.setFont(font)
        self.pushButton_askEve.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_askEve.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_askEve.setObjectName("pushButton_askEve")
        self.pushButton_credits = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_credits.setGeometry(QtCore.QRect(752, 330, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_credits.setFont(font)
        self.pushButton_credits.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_credits.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_credits.setObjectName("pushButton_credits")
        self.label_eve = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_eve.setGeometry(QtCore.QRect(230, 230, 201, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eve.sizePolicy().hasHeightForWidth())
        self.label_eve.setSizePolicy(sizePolicy)
        self.label_eve.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_eve.setText("")
        self.label_eve.setPixmap(QtGui.QPixmap("M:\\Mk_Coding\\lang_Python\\Projects\\Eve-Classification-Model/Ui\\eve_poses/eve_explaining.png"))
        self.label_eve.setScaledContents(False)
        self.label_eve.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_eve.setObjectName("label_eve")
        self.label_speech_bubble = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_speech_bubble.setGeometry(QtCore.QRect(380, 370, 241, 151))
        self.label_speech_bubble.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_speech_bubble.setText("")
        self.label_speech_bubble.setPixmap(QtGui.QPixmap("M:\\Mk_Coding\\lang_Python\\Projects\\Eve-Classification-Model/Ui\\speech_bubble_img.png"))
        self.label_speech_bubble.setScaledContents(True)
        self.label_speech_bubble.setObjectName("label_speech_bubble")
        self.label_dialogue = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_dialogue.setGeometry(QtCore.QRect(390, 430, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(20)
        self.label_dialogue.setFont(font)
        self.label_dialogue.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(79, 79, 79);\n"
"")
        self.label_dialogue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dialogue.setWordWrap(True)
        self.label_dialogue.setObjectName("label_dialogue")
        self.frame_accuracy = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_accuracy.setGeometry(QtCore.QRect(1062, -3, 681, 558))
        self.frame_accuracy.setStyleSheet("QFrame#frame_accuracy{\n"
"background-color: rgba(255, 85, 127,1);\n"
"border-radius: 15px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"}")
        self.frame_accuracy.setObjectName("frame_accuracy")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_accuracy)
        self.verticalLayout.setContentsMargins(7, 10, 7, 8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cats = QtWidgets.QLabel(parent=self.frame_accuracy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_cats.setFont(font)
        self.label_cats.setStyleSheet("border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"background-color: rgba(255, 255, 255,0.7);\n"
"color: rgb(70, 70, 70);")
        self.label_cats.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_cats.setObjectName("label_cats")
        self.verticalLayout.addWidget(self.label_cats)
        self.scrollArea_cats = QtWidgets.QScrollArea(parent=self.frame_accuracy)
        self.scrollArea_cats.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_cats.setStyleSheet("QScrollArea{\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"}")
        self.scrollArea_cats.setWidgetResizable(True)
        self.scrollArea_cats.setObjectName("scrollArea_cats")
        self.scrollAreaWidgetContents_cats = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_cats.setGeometry(QtCore.QRect(0, 0, 667, 185))
        self.scrollAreaWidgetContents_cats.setStyleSheet("QWidget#scrollAreaWidgetContents_cats{\n"
"background-color: rgba(255, 255, 255,0.7);\n"
"}")
        self.scrollAreaWidgetContents_cats.setObjectName("scrollAreaWidgetContents_cats")
        self.scrollArea_cats.setWidget(self.scrollAreaWidgetContents_cats)
        self.verticalLayout.addWidget(self.scrollArea_cats)
        spacerItem = QtWidgets.QSpacerItem(2, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_dogs = QtWidgets.QLabel(parent=self.frame_accuracy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_dogs.setFont(font)
        self.label_dogs.setStyleSheet("border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"background-color: rgba(255, 255, 255,0.7);\n"
"color: rgb(70, 70, 70);")
        self.label_dogs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dogs.setObjectName("label_dogs")
        self.verticalLayout.addWidget(self.label_dogs)
        self.scrollArea_dogs = QtWidgets.QScrollArea(parent=self.frame_accuracy)
        self.scrollArea_dogs.setStyleSheet("QScrollArea{\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"}")
        self.scrollArea_dogs.setWidgetResizable(True)
        self.scrollArea_dogs.setObjectName("scrollArea_dogs")
        self.scrollAreaWidgetContents_dogs = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_dogs.setGeometry(QtCore.QRect(0, 0, 667, 184))
        self.scrollAreaWidgetContents_dogs.setStyleSheet("QWidget#scrollAreaWidgetContents_dogs{\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"background-color: rgba(255, 255, 255,0.7);\n"
"}")
        self.scrollAreaWidgetContents_dogs.setObjectName("scrollAreaWidgetContents_dogs")
        self.scrollArea_dogs.setWidget(self.scrollAreaWidgetContents_dogs)
        self.verticalLayout.addWidget(self.scrollArea_dogs)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_accuracy = QtWidgets.QPushButton(parent=self.frame_accuracy)
        self.pushButton_accuracy.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_accuracy.setFont(font)
        self.pushButton_accuracy.setStyleSheet("QPushButton {\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-color: rgba(0, 0 ,0,0.6);\n"
"    border-radius: 10px;\n"
"    border: 3px solid;\n"
"    border-top: 1px solid;\n"
"    border-left: 1px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(170, 255, 255,0.9);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 3px solid;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"}\n"
"\n"
"")
        self.pushButton_accuracy.setObjectName("pushButton_accuracy")
        self.horizontalLayout_3.addWidget(self.pushButton_accuracy)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_importMore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_importMore.setGeometry(QtCore.QRect(710, 250, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_importMore.setFont(font)
        self.pushButton_importMore.setStyleSheet("QPushButton {\n"
"border: 2px solid;\n"
"border-color: rgba(0,0,0,0.4);\n"
"background-color: rgba(170, 255, 127,0.2);\n"
"border-radius: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    color: rgb(222, 222, 222);\n"
"    background-color: rgb(102, 104, 255);\n"
"    background-color: rgb(0, 170, 127);\n"
"}\n"
"\n"
"")
        self.pushButton_importMore.setText("")
        self.pushButton_importMore.setObjectName("pushButton_importMore")
        self.pushButton_resetImports = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_resetImports.setGeometry(QtCore.QRect(710, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_resetImports.setFont(font)
        self.pushButton_resetImports.setStyleSheet("QPushButton {\n"
"border: 2px solid black;\n"
"border-color: rgba(0,0,0,0.4);\n"
"background-color: rgba(255, 138, 169,0.2);\n"
"border-radius: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(255, 138, 169);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    background-color: rgb(255, 228, 230);\n"
"}\n"
"")
        self.pushButton_resetImports.setText("")
        self.pushButton_resetImports.setObjectName("pushButton_resetImports")
        self.pushButton_collapseAccuracy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_collapseAccuracy.setGeometry(QtCore.QRect(346, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_collapseAccuracy.setFont(font)
        self.pushButton_collapseAccuracy.setStyleSheet("QPushButton {\n"
"border: 2px solid;\n"
"border-color: rgba(0,0,0,0.4);\n"
"background-color: rgba(170, 255, 255,0.2);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid;\n"
"    border-color: rgb(95, 95, 95);\n"
"    background-color: rgb(102, 104, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_collapseAccuracy.setText("")
        self.pushButton_collapseAccuracy.setObjectName("pushButton_collapseAccuracy")
        self.pushButton_expandAccuracy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_expandAccuracy.setGeometry(QtCore.QRect(1020, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_expandAccuracy.setFont(font)
        self.pushButton_expandAccuracy.setStyleSheet("QPushButton {\n"
"border: 2px solid;\n"
"border-color: rgba(0,0,0,0.4);\n"
"background-color: rgba(170, 255, 255,0.2);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid;\n"
"    border-color: rgb(95, 95, 95);\n"
"    background-color: rgb(102, 104, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_expandAccuracy.setText("")
        self.pushButton_expandAccuracy.setObjectName("pushButton_expandAccuracy")
        self.label_catBasket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_catBasket.setGeometry(QtCore.QRect(220, 130, 101, 101))
        self.label_catBasket.setStyleSheet("QLabel{\n"
"    border: 3px solid black;\n"
"    border-top-right-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-color: pink; \n"
"}\n"
"\n"
"")
        self.label_catBasket.setText("")
        self.label_catBasket.setScaledContents(False)
        self.label_catBasket.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_catBasket.setObjectName("label_catBasket")
        self.label_dogBasket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_dogBasket.setGeometry(QtCore.QRect(720, 130, 101, 101))
        self.label_dogBasket.setStyleSheet("QLabel{\n"
"    border: 3px solid black;\n"
"    border-top-right-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-color: pink; \n"
"}\n"
"\n"
"")
        self.label_dogBasket.setText("")
        self.label_dogBasket.setScaledContents(False)
        self.label_dogBasket.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dogBasket.setObjectName("label_dogBasket")
        self.pushButton_slowDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_slowDown.setGeometry(QtCore.QRect(764, 270, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_slowDown.setFont(font)
        self.pushButton_slowDown.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_slowDown.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("M:\\Mk_Coding\\lang_Python\\Projects\\Eve-Classification-Model/Ui\\reset_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_slowDown.setIcon(icon)
        self.pushButton_slowDown.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_slowDown.setObjectName("pushButton_slowDown")
        self.pushButton_speedUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_speedUp.setGeometry(QtCore.QRect(760, 327, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_speedUp.setFont(font)
        self.pushButton_speedUp.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_speedUp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("M:\\Mk_Coding\\lang_Python\\Projects\\Eve-Classification-Model/Ui\\speed_up_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_speedUp.setIcon(icon1)
        self.pushButton_speedUp.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_speedUp.setObjectName("pushButton_speedUp")
        self.frame_results = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_results.setGeometry(QtCore.QRect(1062, -3, 681, 558))
        self.frame_results.setMinimumSize(QtCore.QSize(681, 558))
        self.frame_results.setMaximumSize(QtCore.QSize(681, 558))
        self.frame_results.setStyleSheet("QFrame#frame_results{\n"
"    background-color: rgb(85, 255, 255);\n"
"border-radius: 15px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"}")
        self.frame_results.setObjectName("frame_results")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_results)
        self.verticalLayout_2.setContentsMargins(7, 10, 7, 8)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_results = QtWidgets.QLabel(parent=self.frame_results)
        self.label_results.setMinimumSize(QtCore.QSize(667, 56))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_results.setFont(font)
        self.label_results.setStyleSheet("border-radius:15px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"background-color: rgba(255, 255, 255,0.7);\n"
"color: rgb(70, 70, 70);")
        self.label_results.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_results.setObjectName("label_results")
        self.verticalLayout_2.addWidget(self.label_results)
        self.frame_inside_results = QtWidgets.QFrame(parent=self.frame_results)
        self.frame_inside_results.setMinimumSize(QtCore.QSize(0, 423))
        self.frame_inside_results.setStyleSheet("background-color: rgba(255, 255, 255, 1);\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius:0px;")
        self.frame_inside_results.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inside_results.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inside_results.setObjectName("frame_inside_results")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_inside_results)
        self.verticalLayout_6.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.label_total_images = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_total_images.setFont(font)
        self.label_total_images.setObjectName("label_total_images")
        self.horizontalLayout_12.addWidget(self.label_total_images)
        self.label_value_total_images = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_total_images.setFont(font)
        self.label_value_total_images.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_value_total_images.setObjectName("label_value_total_images")
        self.horizontalLayout_12.addWidget(self.label_value_total_images)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_correctly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(16)
        self.label_correctly_classified.setFont(font)
        self.label_correctly_classified.setObjectName("label_correctly_classified")
        self.horizontalLayout_5.addWidget(self.label_correctly_classified)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cats_correctly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_cats_correctly_classified.setFont(font)
        self.label_cats_correctly_classified.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_cats_correctly_classified.setObjectName("label_cats_correctly_classified")
        self.horizontalLayout.addWidget(self.label_cats_correctly_classified)
        self.label_value_correct_cats = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_value_correct_cats.setFont(font)
        self.label_value_correct_cats.setStyleSheet("font: 25pt \"Impact\";\n"
"color: rgb(85, 255, 0);")
        self.label_value_correct_cats.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_value_correct_cats.setObjectName("label_value_correct_cats")
        self.horizontalLayout.addWidget(self.label_value_correct_cats)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_dogs_correctly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_dogs_correctly_classified.setFont(font)
        self.label_dogs_correctly_classified.setObjectName("label_dogs_correctly_classified")
        self.horizontalLayout_2.addWidget(self.label_dogs_correctly_classified)
        self.label_value_correct_dogs = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_correct_dogs.setFont(font)
        self.label_value_correct_dogs.setStyleSheet("\n"
"color: rgb(85, 255, 0);")
        self.label_value_correct_dogs.setObjectName("label_value_correct_dogs")
        self.horizontalLayout_2.addWidget(self.label_value_correct_dogs)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_total_correctly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_total_correctly_classified.setFont(font)
        self.label_total_correctly_classified.setObjectName("label_total_correctly_classified")
        self.horizontalLayout_7.addWidget(self.label_total_correctly_classified)
        self.label_value_correct_total = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_correct_total.setFont(font)
        self.label_value_correct_total.setStyleSheet("\n"
"color: rgb(85, 255, 0);")
        self.label_value_correct_total.setObjectName("label_value_correct_total")
        self.horizontalLayout_7.addWidget(self.label_value_correct_total)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.label_incorrectly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(16)
        self.label_incorrectly_classified.setFont(font)
        self.label_incorrectly_classified.setObjectName("label_incorrectly_classified")
        self.horizontalLayout_6.addWidget(self.label_incorrectly_classified)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_cats_incorrectly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_cats_incorrectly_classified.setFont(font)
        self.label_cats_incorrectly_classified.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_cats_incorrectly_classified.setObjectName("label_cats_incorrectly_classified")
        self.horizontalLayout_9.addWidget(self.label_cats_incorrectly_classified)
        self.label_value_incorrect_cats = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_incorrect_cats.setFont(font)
        self.label_value_incorrect_cats.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_value_incorrect_cats.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_value_incorrect_cats.setObjectName("label_value_incorrect_cats")
        self.horizontalLayout_9.addWidget(self.label_value_incorrect_cats)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_dogs_incorrectly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_dogs_incorrectly_classified.setFont(font)
        self.label_dogs_incorrectly_classified.setObjectName("label_dogs_incorrectly_classified")
        self.horizontalLayout_10.addWidget(self.label_dogs_incorrectly_classified)
        self.label_value_incorrect_dogs = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_incorrect_dogs.setFont(font)
        self.label_value_incorrect_dogs.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_value_incorrect_dogs.setObjectName("label_value_incorrect_dogs")
        self.horizontalLayout_10.addWidget(self.label_value_incorrect_dogs)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_total_incorrectly_classified = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_total_incorrectly_classified.setFont(font)
        self.label_total_incorrectly_classified.setObjectName("label_total_incorrectly_classified")
        self.horizontalLayout_11.addWidget(self.label_total_incorrectly_classified)
        self.label_value_incorrect_total = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_incorrect_total.setFont(font)
        self.label_value_incorrect_total.setStyleSheet("color: rgb(255, 85, 127);\n"
"")
        self.label_value_incorrect_total.setObjectName("label_value_incorrect_total")
        self.horizontalLayout_11.addWidget(self.label_value_incorrect_total)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(3, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.label_accuracy_result = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("HP Simplified")
        font.setPointSize(17)
        self.label_accuracy_result.setFont(font)
        self.label_accuracy_result.setObjectName("label_accuracy_result")
        self.horizontalLayout_14.addWidget(self.label_accuracy_result)
        self.label_value_accuracy = QtWidgets.QLabel(parent=self.frame_inside_results)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_accuracy.setFont(font)
        self.label_value_accuracy.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_value_accuracy.setObjectName("label_value_accuracy")
        self.horizontalLayout_14.addWidget(self.label_value_accuracy)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(3, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        spacerItem22 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem22)
        self.verticalLayout_2.addWidget(self.frame_inside_results)
        spacerItem23 = QtWidgets.QSpacerItem(2, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem23)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem24)
        self.pushButton_save_output = QtWidgets.QPushButton(parent=self.frame_results)
        self.pushButton_save_output.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_save_output.setFont(font)
        self.pushButton_save_output.setStyleSheet("QPushButton {\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-color: rgba(0, 0 ,0,0.6);\n"
"    border-radius: 10px;\n"
"    border: 3px solid;\n"
"    border-top: 1px solid;\n"
"    border-left: 1px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(78, 255, 176);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 3px solid;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"}\n"
"\n"
"")
        self.pushButton_save_output.setObjectName("pushButton_save_output")
        self.horizontalLayout_15.addWidget(self.pushButton_save_output)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem25)
        self.pushButton_thankyou = QtWidgets.QPushButton(parent=self.frame_results)
        self.pushButton_thankyou.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton_thankyou.setFont(font)
        self.pushButton_thankyou.setStyleSheet("QPushButton {\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(255, 255, 127);\n"
"    border-color: rgba(0, 0 ,0,0.6);\n"
"    border-radius: 10px;\n"
"    border: 3px solid;\n"
"    border-top: 1px solid;\n"
"    border-left: 1px solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 197, 248);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 3px solid;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"}\n"
"\n"
"")
        self.pushButton_thankyou.setObjectName("pushButton_thankyou")
        self.horizontalLayout_15.addWidget(self.pushButton_thankyou)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.label_bg.raise_()
        self.label_inputImages.raise_()
        self.pushButton_importPics.raise_()
        self.pushButton_classify.raise_()
        self.pushButton_askEve.raise_()
        self.pushButton_credits.raise_()
        self.frame_accuracy.raise_()
        self.pushButton_minimize.raise_()
        self.pushButton_close.raise_()
        self.pushButton_expandAccuracy.raise_()
        self.label_catBasket.raise_()
        self.label_dogBasket.raise_()
        self.pushButton_importMore.raise_()
        self.pushButton_resetImports.raise_()
        self.pushButton_slowDown.raise_()
        self.pushButton_speedUp.raise_()
        self.frame_results.raise_()
        self.pushButton_collapseAccuracy.raise_()
        self.label_eve.raise_()
        self.label_speech_bubble.raise_()
        self.label_dialogue.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_importPics.setText(_translate("MainWindow", "[click to import images or drag images]"))
        self.pushButton_classify.setText(_translate("MainWindow", "Classify!"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">close</p></body></html>"))
        self.pushButton_close.setText(_translate("MainWindow", "X"))
        self.pushButton_minimize.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">minimize</p></body></html>"))
        self.pushButton_minimize.setText(_translate("MainWindow", "-"))
        self.pushButton_askEve.setText(_translate("MainWindow", "Ask Eve"))
        self.pushButton_credits.setText(_translate("MainWindow", "Credits"))
        self.label_dialogue.setText(_translate("MainWindow", "Hello There!"))
        self.label_cats.setText(_translate("MainWindow", "Cats"))
        self.label_dogs.setText(_translate("MainWindow", "Dogs"))
        self.pushButton_accuracy.setText(_translate("MainWindow", " All classifications are correct, Eve! :D "))
        self.pushButton_importMore.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">import more images</p></body></html>"))
        self.pushButton_resetImports.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">reset input images</p></body></html>"))
        self.pushButton_collapseAccuracy.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">collapse</p></body></html>"))
        self.pushButton_expandAccuracy.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">expand</p></body></html>"))
        self.label_results.setText(_translate("MainWindow", "Results"))
        self.label_total_images.setText(_translate("MainWindow", "Total Images:"))
        self.label_value_total_images.setText(_translate("MainWindow", "00"))
        self.label_correctly_classified.setText(_translate("MainWindow", "Correctly Classified"))
        self.label_cats_correctly_classified.setText(_translate("MainWindow", "Cats"))
        self.label_value_correct_cats.setText(_translate("MainWindow", "00"))
        self.label_dogs_correctly_classified.setText(_translate("MainWindow", "Dogs"))
        self.label_value_correct_dogs.setText(_translate("MainWindow", "00"))
        self.label_total_correctly_classified.setText(_translate("MainWindow", "Total"))
        self.label_value_correct_total.setText(_translate("MainWindow", "00"))
        self.label_incorrectly_classified.setText(_translate("MainWindow", "Incorrectly Classified"))
        self.label_cats_incorrectly_classified.setText(_translate("MainWindow", "Cats"))
        self.label_value_incorrect_cats.setText(_translate("MainWindow", "00"))
        self.label_dogs_incorrectly_classified.setText(_translate("MainWindow", "Dogs"))
        self.label_value_incorrect_dogs.setText(_translate("MainWindow", "00"))
        self.label_total_incorrectly_classified.setText(_translate("MainWindow", "Total"))
        self.label_value_incorrect_total.setText(_translate("MainWindow", "00"))
        self.label_accuracy_result.setText(_translate("MainWindow", "Accuracy:"))
        self.label_value_accuracy.setText(_translate("MainWindow", "00.0%"))
        self.pushButton_save_output.setText(_translate("MainWindow", "Save Output"))
        self.pushButton_thankyou.setText(_translate("MainWindow", "Thank You Eve :)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
