# Form implementation generated from reading ui file 'D:/Mk_Coding_Stuff/lang_Python/PyQt5_programs/Eve/Ui/eve_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 533)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_input = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_input.setStyleSheet("\n"
"QWidget#widget_input{\n"
"border-radius: 10px;\n"
"border:1px solid purple;\n"
"};\n"
"background-color: rgb(220, 250, 255);\n"
"")
        self.widget_input.setObjectName("widget_input")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_input)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_cat_2 = QtWidgets.QGridLayout()
        self.gridLayout_cat_2.setObjectName("gridLayout_cat_2")
        self.verticalLayout_4.addLayout(self.gridLayout_cat_2)
        self.horizontalLayout.addWidget(self.widget_input)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_cat = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_cat.setMinimumSize(QtCore.QSize(249, 177))
        self.widget_cat.setStyleSheet("QWidget#widget_cat{\n"
"border-radius: 10px;\n"
"border:1px solid purple;\n"
"};\n"
"background-color: rgb(236, 236, 236);\n"
"")
        self.widget_cat.setObjectName("widget_cat")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_cat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cat = QtWidgets.QLabel(parent=self.widget_cat)
        font = QtGui.QFont()
        font.setFamily("Rupee Foradian")
        font.setPointSize(16)
        self.label_cat.setFont(font)
        self.label_cat.setObjectName("label_cat")
        self.verticalLayout.addWidget(self.label_cat)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_cat = QtWidgets.QGridLayout()
        self.gridLayout_cat.setObjectName("gridLayout_cat")
        self.verticalLayout.addLayout(self.gridLayout_cat)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 100)
        self.verticalLayout_2.addWidget(self.widget_cat)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_importPics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_importPics.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Rupee Foradian")
        font.setPointSize(13)
        self.pushButton_importPics.setFont(font)
        self.pushButton_importPics.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgb(44, 128, 255);\n"
"border: 1px solid;\n"
"border-radius: 8px;\n"
"    border-color: rgb(51, 61, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.pushButton_importPics.setObjectName("pushButton_importPics")
        self.gridLayout.addWidget(self.pushButton_importPics, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton_askEve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_askEve.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Rupee Foradian")
        font.setPointSize(13)
        self.pushButton_askEve.setFont(font)
        self.pushButton_askEve.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgb(44, 128, 255);\n"
"border:1px solid;\n"
"    border-color: rgb(51, 61, 255);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"}")
        self.pushButton_askEve.setObjectName("pushButton_askEve")
        self.gridLayout.addWidget(self.pushButton_askEve, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.widget_dog = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_dog.setMinimumSize(QtCore.QSize(249, 176))
        self.widget_dog.setStyleSheet("QWidget#widget_dog{\n"
"border-radius: 10px;\n"
"border:1px solid purple;\n"
"};\n"
"background-color: rgb(236, 236, 236);")
        self.widget_dog.setObjectName("widget_dog")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_dog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_dog = QtWidgets.QLabel(parent=self.widget_dog)
        font = QtGui.QFont()
        font.setFamily("Rupee Foradian")
        font.setPointSize(16)
        self.label_dog.setFont(font)
        self.label_dog.setObjectName("label_dog")
        self.verticalLayout_3.addWidget(self.label_dog)
        spacerItem3 = QtWidgets.QSpacerItem(226, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_dog = QtWidgets.QGridLayout()
        self.gridLayout_dog.setObjectName("gridLayout_dog")
        self.verticalLayout_3.addLayout(self.gridLayout_dog)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 100)
        self.verticalLayout_2.addWidget(self.widget_dog)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cat.setText(_translate("MainWindow", "Cats"))
        self.pushButton_importPics.setText(_translate("MainWindow", "Import Pics"))
        self.pushButton_askEve.setText(_translate("MainWindow", "Ask Eve"))
        self.label_dog.setText(_translate("MainWindow", "Dogs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
