# Form implementation generated from reading ui file 'M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui/eve_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1060, 552)
        MainWindow.setStyleSheet("border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.046, x2:1, y2:0.972, stop:0 rgba(229, 253, 255, 255), stop:0.994318 rgba(131, 250, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.187, y1:0.478, x2:0.907689, y2:0.813, stop:0 rgba(255, 255, 255, 226), stop:0.994318 rgba(199, 199, 199, 197));\n"
"background-color: qlineargradient(spread:pad, x1:0.187, y1:0.478, x2:0.907689, y2:0.813, stop:0 rgba(255, 255, 255, 239), stop:0.994318 rgba(215, 215, 215, 217));\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_bg = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 1060, 552))
        self.label_bg.setText("")
        self.label_bg.setPixmap(QtGui.QPixmap("M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui\\bg_img.png"))
        self.label_bg.setObjectName("label_bg")
        self.label_inputImages = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_inputImages.setGeometry(QtCore.QRect(353, 130, 331, 211))
        self.label_inputImages.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_inputImages.setText("")
        self.label_inputImages.setScaledContents(True)
        self.label_inputImages.setObjectName("label_inputImages")
        self.pushButton_importPics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_importPics.setGeometry(QtCore.QRect(350, 130, 334, 211))
        self.pushButton_importPics.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(True)
        self.pushButton_importPics.setFont(font)
        self.pushButton_importPics.setStyleSheet("QPushButton {\n"
"    background-color: rgb(250, 198, 255);\n"
"    background-color: rgb(253, 235, 255);\n"
"border-radius: 10px;\n"
"    color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(253, 238, 255);\n"
"    font: 12pt \"Rupee Foradian\";\n"
"}")
        self.pushButton_importPics.setObjectName("pushButton_importPics")
        self.pushButton_classify = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_classify.setGeometry(QtCore.QRect(400, 410, 241, 61))
        self.pushButton_classify.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        self.pushButton_classify.setFont(font)
        self.pushButton_classify.setStyleSheet("QPushButton {\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(250, 198, 255);\n"
"    border: 3px solid black;\n"
"    border-color: rgba(0, 0 ,0,0.6);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border: 4px solid black;\n"
"    font: 87 13pt \"Segoe UI Black\";\n"
"    background-color: rgba(255, 255, 0,0.7);\n"
"\n"
"}")
        self.pushButton_classify.setObjectName("pushButton_classify")
        self.pushButton_cat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cat.setGeometry(QtCore.QRect(220, 130, 101, 101))
        self.pushButton_cat.setStyleSheet("QPushButton{\n"
"    border: 3px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid black;\n"
"}\n"
"")
        self.pushButton_cat.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui\\cat_button_img.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cat.setIcon(icon)
        self.pushButton_cat.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_cat.setObjectName("pushButton_cat")
        self.pushButton_dog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_dog.setGeometry(QtCore.QRect(720, 130, 101, 101))
        self.pushButton_dog.setStyleSheet("QPushButton{\n"
"    border: 3px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-color: rgb(255, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"")
        self.pushButton_dog.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui\\dog_button_img.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_dog.setIcon(icon1)
        self.pushButton_dog.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_dog.setObjectName("pushButton_dog")
        self.pushButton_close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1020, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"border: 2px solid black;\n"
"border-color: rgba(0,0,0,0.4);\n"
"color: rgba(72, 72, 72,0.7);\n"
"background-color: rgba(255, 138, 169,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"color: rgb(72, 72, 72);\n"
"background-color: rgb(255, 138, 169);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    background-color: rgb(255, 228, 230);\n"
"}\n"
"")
        self.pushButton_close.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_minimize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_minimize.setGeometry(QtCore.QRect(980, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_minimize.setFont(font)
        self.pushButton_minimize.setStyleSheet("QPushButton {\n"
"border: 2px solid black;\n"
"border-color: rgba(0,0,0,0.4);\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(170, 255, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 14pt \"Segoe UI Black\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color: rgb(0,0,0);\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 3px solid black;\n"
"    color: rgb(222, 222, 222);\n"
"    background-color: rgb(102, 104, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_minimize.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.pushButton_askEve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_askEve.setGeometry(QtCore.QRect(759, 290, 112, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_askEve.setFont(font)
        self.pushButton_askEve.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_askEve.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_askEve.setObjectName("pushButton_askEve")
        self.pushButton_credits = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_credits.setGeometry(QtCore.QRect(752, 330, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_credits.setFont(font)
        self.pushButton_credits.setStyleSheet("QPushButton {\n"
"color: rgba(79, 79, 79,0.7);\n"
"background-color: rgba(250, 198, 255,0.2);\n"
"border-radius: 10px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(79, 79, 79);\n"
"background-color: rgba(255, 255, 0,0.7);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 87 8pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"")
        self.pushButton_credits.setIconSize(QtCore.QSize(91, 91))
        self.pushButton_credits.setObjectName("pushButton_credits")
        self.label_eve = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_eve.setGeometry(QtCore.QRect(230, 230, 201, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eve.sizePolicy().hasHeightForWidth())
        self.label_eve.setSizePolicy(sizePolicy)
        self.label_eve.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_eve.setText("")
        self.label_eve.setPixmap(QtGui.QPixmap("M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui\\eve_poses/eve_explaining.png"))
        self.label_eve.setScaledContents(False)
        self.label_eve.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_eve.setObjectName("label_eve")
        self.label_speech_bubble = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_speech_bubble.setGeometry(QtCore.QRect(380, 370, 241, 151))
        self.label_speech_bubble.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_speech_bubble.setText("")
        self.label_speech_bubble.setPixmap(QtGui.QPixmap("M:/Mk_Coding/lang_Python/Projects/Eve-Classification-Model/Ui\\speech_bubble_img.png"))
        self.label_speech_bubble.setScaledContents(True)
        self.label_speech_bubble.setObjectName("label_speech_bubble")
        self.label_dialogue = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_dialogue.setGeometry(QtCore.QRect(390, 430, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(20)
        self.label_dialogue.setFont(font)
        self.label_dialogue.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(79, 79, 79);\n"
"")
        self.label_dialogue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dialogue.setWordWrap(True)
        self.label_dialogue.setObjectName("label_dialogue")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_importPics.setText(_translate("MainWindow", "[click to import images or drag images]"))
        self.pushButton_classify.setText(_translate("MainWindow", "Classify!"))
        self.pushButton_close.setText(_translate("MainWindow", "X"))
        self.pushButton_minimize.setText(_translate("MainWindow", "-"))
        self.pushButton_askEve.setText(_translate("MainWindow", "Ask Eve"))
        self.pushButton_credits.setText(_translate("MainWindow", "Credits"))
        self.label_dialogue.setText(_translate("MainWindow", "Hello There!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
